version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-Gifts}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_PWD-iaw}
      #MYSQL_USER: ${MYSQL_USER:-mysqlAdmin}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD:-adminPwd}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  database_data: